### ISSUE TITLE
Wrong background color in light mode after the recent update

### ISSUE THREAD

**Issue by AkemiHomura-maow** [block-wallet/ethereum-gas-prices-browser-extension#17]
![image](https://user-images.githubusercontent.com/34213712/172001833-ff99e6bd-26a1-4668-9e79-57d55ac63459.png)

**Comment by AkemiHomura-maow** [comment]
> ![image](https://user-images.githubusercontent.com/34213712/172001833-ff99e6bd-26a1-4668-9e79-57d55ac63459.png)

Black used to work perfectly fine, until the recent update which changes the color to grey now. Bad contrast under light mode.

**Comment by bbdefender1** [comment]
Agree with this, the black was great but now after the most recent update I can barely read it.
