### ISSUE TITLE
Latest version displays "..." for gas price instead of number

### ISSUE THREAD

**Issue by creativedrewy** [block-wallet/ethereum-gas-prices-browser-extension#3]
For a few weeks now the gas price number has not been showing in the top-right icon preview, instead just showing "...". This is what it looks like:

![Screen Shot 2021-11-02 at 10 11 54 AM](https://user-images.githubusercontent.com/2018851/139913094-9a4a2c7e-4978-4e4a-b366-7a8e2449eba9.png)

Browser: Brave v 1.31.88 Chromium 95
OS: MacOS Big Sur

**Comment by philippe-git** [comment]
Is this still happening?

**Comment by creativedrewy** [comment]
Yep! I just grabbed a screenshot:
![Screen Shot 2021-12-09 at 10 45 27 AM](https://user-images.githubusercontent.com/2018851/145456930-ea539697-5cdf-49f2-a1c2-4290b7b0099a.png)

**Comment by mohamedmansour** [comment]
Not anymore, the reason it happened at first many months ago is because you need to select a Gas from the pop-up, there was no default.
