### ISSUE TITLE
Notice: Firefox extension not upgradable anymore until manifest v3 support

### ISSUE THREAD

**Issue by philippe-git** [block-wallet/ethereum-gas-prices-browser-extension#6]
*The below only concerns the extension as published on Firefox. The extension published on the Chrome Web Store (available on Chrome, Brave, and Chromium alternatives) works without issues.*

The currently published version of this extension retrieves data from an API that is no longer online. A more recent version of this extension exists, but uses a modern format that Firefox has been planning to support for some time but doesn't support yet (see https://discourse.mozilla.org/t/when-will-it-be-possible-to-test-add-ons-under-manifest-3-using-firefox/91113/5). Until this format is supported by Firefox, the extension cannot be updated to the recent version that contains updated API endpoints. In other words, until Firefox supports manifest v3 (which should happen in early 2022?), this extension will unfortunately remain non-functional. Apologies about this situation.

**Comment by jkcdarunday** [comment]
Looks like firefox now has experimental support for Manifest v3 but it still needs a toggle in the about:config page to work.
https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/
